import { BodyPartId } from './bodyParts';
import { SpecialityId } from './specialities';

export const BODY_SPECIALITY_MAP: Record<BodyPartId, SpecialityId[]> = {
  HEAD_BRAIN:  ['NEUROLOGY', 'ENT', 'OPHTHALMOLOGY', 'DENTISTRY', 'PSYCHIATRY', 'GENERAL_MEDICINE'],
  CHEST_HEART: ['CARDIOLOGY', 'PULMONOLOGY', 'GENERAL_MEDICINE'],
  ABDOMEN:     ['GASTRO', 'NEPHROLOGY', 'GYNAECOLOGY', 'UROLOGY', 'ENDOCRINOLOGY', 'GENERAL_MEDICINE'],
  BACK_SPINE:  ['ORTHO', 'NEUROLOGY', 'GENERAL_MEDICINE'],
  ARMS_HANDS:  ['ORTHO', 'DERMATOLOGY', 'GENERAL_MEDICINE'],
  LEGS_FEET:   ['ORTHO', 'DERMATOLOGY', 'GENERAL_MEDICINE'],
  SKIN:        ['DERMATOLOGY', 'GENERAL_MEDICINE'],
  GENERAL:     ['GENERAL_MEDICINE', 'ENDOCRINOLOGY', 'PSYCHIATRY', 'OTHER'],
};
